#!/bin/sh
#
# Start mmc_reader to read from mmc
#

start() {
  echo "DRY RUN: mmc_reader"
  ## TODO ##start-stop-daemon -S -q -b -m -p /var/run/mmc_reader.pid --exec \
  ## TODO ##  mmc_reader -- /dev/mmcblk0 8192
}
stop() {
  echo "KILL: mmc_reader"
  ## TODO ##start-stop-daemon -K -q -p /var/run/mmc_reader.pid
}
restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
